CourseManSystem/CourseManSystem/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using CourseManSystem.BL.Contracts.Servicees;
using CourseManSystem.Identity.Infrastructure;
using CourseManSystem.Models;
using CourseManSystem.Transformers;
using Microsoft.AspNet.Identity;
using WebGrease.Css.Extensions;

namespace CourseManSystem.Controllers
{
    [Authorize]
    public class CourseController : Controller
    {
        private readonly ICourseService _courseService;
        private readonly IUserService _userService;

        public CourseController(ICourseService courseService, IUserService userService, ITopicService topicService)
        {
            _userService = userService;
            _courseService = courseService;
        }

        // GET: Course
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            var courseList = _courseService.GetAll().Select(o => DtoTransformer.Convert(o)).ToList();
            return View(courseList);
        }

        [HttpGet]
        public ActionResult AssignedCourses(string id)
        {
            if (id == null)
            {
                return View("Error");
            }
            List<CoursePlModel> courseList = _userService.GetOneById(Guid.Parse(id))
                                             .Courses.Select(o => DtoTransformer.Convert(o)).ToList();
            return View(courseList);
        }

        [HttpGet]

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CoursePlModel objToCreate)
        {
            if (ModelState.IsValid)
            {
                objToCreate.Members.Add(new UserPlModel{Id = Guid.Parse(User.Identity.GetUserId())});
                var courseId = _courseService.Create(objToCreate);
                if (courseId == null)
                {
                    return View("Error");
                }
                objToCreate.Id = courseId.Value;
            }
            return RedirectToAction("TopicList","Topic", new {id = objToCreate.Id.ToString()});
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return View("Error");
            }
            var course = _courseService.GetOneById(Guid.Parse(id));
            return View(DtoTransformer.Convert(course));
        }

        [HttpPost]
        public ActionResult Edit(CoursePlModel model)
        {
            if (ModelState.IsValid)
            {
                var succeed = _courseService.Update(model);
                if (succeed)
                {
                    return View(model);
                }
            }
            return View("Error");
        }

        //https://antiyes.com/2015/05/26/asp-net-mvc-calendar-helper/
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Details(Guid? id, bool isUserId)
        {
            if (id == null)
            {
                return View("Error");
            }

            var topicList = new List<TopicPlModel>
            {
                //new TopicPlModel{Day = DateTime.Today, Title = "mathematics",Description = "mathematics description"},
                //new TopicPlModel{Day = DateTime.Today, Title = "history", Description = "History Description"},
                //new TopicPlModel{Day = DateTime.Today.AddDays(96), Title = "Geography"},
                //new TopicPlModel{Day = DateTime.Today.AddDays(40), Title = "Literature"},
                //new TopicPlModel{Day = DateTime.Today.AddDays(600), Title = "English"}
            };

            if (isUserId)
            {
               var userProfile =  _userService.GetOneById(id.Value);
               userProfile.Courses.Select(DtoTransformer.Convert).ForEach(o =>
               {
                   foreach (var topicPlModel in o.Topics.Select(DtoTransformer.Convert))
                       topicList.Add(topicPlModel);
               });
            }
            else
            {
               var foundCourse =  _courseService.GetOneById(id.Value);
               topicList = foundCourse.Topics.Select(DtoTransformer.Convert).ToList();
            }

            return View(topicList);
        }

        public ActionResult Unsubscribe(Guid courseId, Guid userId)
        {
            _courseService.RemoveUserFromCourse(courseId, userId);
            return RedirectToAction("Members", new {id = courseId});
        }

        [HttpGet]
        public ActionResult Subscribe(Guid courseId, Guid userId)
        {
            if (courseId != Guid.Empty || userId != Guid.Empty)
            {
                var succeed = _courseService.AddUserToCourse(courseId, userId);
                if (succeed)
                {
                    return RedirectToAction("NonMembers", new { id = courseId });
                }    
            }
            return View("Error");
        }

        public async Task<ActionResult> NonMembers(Guid id)
        {
            if (id != Guid.Empty)
            {
                ViewBag.courseId = id;
                var members = _courseService
                            .GetOneById(id)
                            .Members.ToList()
                            .Select(o => DtoTransformer.Convert(o))
                            .ToList();
                var userList = await UserProvider.GetAllUsers();
                var nonMembers = userList
                            .Where(o => o.Role == "listener")
                            .ToList()
                            .Where(o => !members.Select(t => t.Id)
                            .ToList()
                            .Contains(o.Id));
                return View(nonMembers.Select(DtoTransformer.Convert));
            }
            return View("Error");
        }

        [HttpGet]
        public async Task<ActionResult> Members(Guid id)
        {
            if (id != Guid.Empty)
            {
                ViewBag.courseId = id;
                var members = _courseService.GetOneById(id).Members.ToList().
                    Select(o => DtoTransformer.Convert(o)).ToList();

                var userList = await UserProvider.GetAllUsers();
                var listeners = userList.Where(o => o.Role == "listener").ToList()
                    .Where(o => members.Select(t => t.Id).ToList().Contains(o.Id));

                return View(listeners.Select(o => DtoTransformer.Convert(o)).ToList());
            }
            return View("Error");
        }

        [HttpGet]
        public ActionResult Delete(Guid id)
        {
            if (id != Guid.Empty)
            {
                var isDeleted = _courseService.Delete(id);
                if (isDeleted)
                {
                    return RedirectToAction("Index");
                }
            }
            return View("Error");
        }
    }
}

CourseManSystem/CourseManSystem/Controllers/TopicController.cs
using System;
using System.Web.Mvc;
using CourseManSystem.BL.Contracts.Servicees;
using CourseManSystem.Models;
using CourseManSystem.Transformers;

namespace CourseManSystem.Controllers
{
    [Authorize]
    public class TopicController : Controller
    {
        private readonly ITopicService _topicService;
        private readonly ICourseService _courseService;

        public TopicController(ITopicService topicService, ICourseService courseService)
        {
            _topicService = topicService;
            _courseService = courseService;
        }

        [HttpGet]
        public ActionResult TopicList(string id)
        {
            if (id == null || Guid.Parse(id)  == Guid.Empty)
            {
                return View("Error");
            }
            var foundCourse = _courseService.GetOneById(Guid.Parse(id));

            return View(DtoTransformer.Convert(foundCourse));
        }

        [Authorize(Roles = "admin, trainer" )]
        [HttpGet]
        public ActionResult Update(Guid? id)
        {
            if (id == null)
            {
                return View("Error");
            }
            var topic = _topicService.GetOneById(id.Value);
            return PartialView(DtoTransformer.Convert(topic));
        }

        [HttpPost]
        public ActionResult Update(TopicPlModel model)
        {
            if (ModelState.IsValid)
            {
               var success =  _topicService.Update(model);
                if (success)
                {
                    return RedirectToAction("TopicList", new { id = model.CourseId.ToString() });
                }
            }
            return View("Error");
        }


        [HttpGet]
        public ActionResult Create(string id)
        {
            ViewBag.id = id;
            return View();
        }

        [HttpPost]
        public ActionResult Create(TopicPlModel model, string id)
        {
            if (ModelState.IsValid && id != null)
            {
                model.CourseId = Guid.Parse(id);
                var successed = _topicService.Create(model);
                if (successed)
                {
                    return RedirectToAction("TopicList", new { id = id });
                }
            }
            return View("Error");
        }

        [HttpGet]
        public ActionResult Delete(string id, string courseId)
        {
            if (id == null || courseId == null)
            {
                return View("Error");
            }
            var successed =  _topicService.Delete(Guid.Parse(id));
            if (successed)
            {
                return RedirectToAction("TopicList", new { id = courseId });
            }
            return View("Error");
        }
        
    }
}

CourseManSystem/CourseManSystem/Views/Topic/Create.cshtml
@model CourseManSystem.Models.TopicPlModel
@{
    ViewBag.Title = "AddTopic";
    Layout = null;
}

<div class="modal-content">
    
    <div class="modal-header">
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
    </div>
    <div class="modal-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <input type="hidden" name="id" value="@ViewBag.id"/>
            <div class="form-horizontal">
                <h4>TopicPlModel</h4>
                <hr/>
                @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
                    </div>
                </div>
                <div>
                    @Html.HiddenFor(model => model.CourseId, new {@Value = @ViewBag.id })
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default"/>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

CourseManSystem/CourseManSystem/Views/Topic/TopicList.cshtml
@model CourseManSystem.Models.CoursePlModel

@{
    ViewBag.Title = "AddTopic";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <meta name="viewport" content="width=device-width"/>
    <title>EditAllUsers</title>
</head>

<h2>AddTopic</h2>

<p>
    @Html.ActionLink("Create New", "Create", "Topic", new{id = Model.Id}, new { @class = "compItem" })
</p>

@if (Model.Topics.Count != 0)
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Topics.FirstOrDefault().Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Topics.FirstOrDefault().Description)
            </th>
            @if (User.IsInRole("admin"))
            {
                <th>
                    @Html.DisplayNameFor(model => model.Topics.FirstOrDefault().Day);
                </th>   
            }
            <th>
                @Html.DisplayNameFor(model => model.Topics.FirstOrDefault().Id)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Topics)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                @if (User.IsInRole("admin"))
                {
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.DisplayFor(modelItem => item.Day, new {htmlAttributes = new {@class = "picker"}})
                            </div>
                        </div>
                    </td>   
                }
                <td>
                    @Html.DisplayFor(modelItem => item.CourseId, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                </td>
                <td>
                    @Html.ActionLink("Edit", "Update", new { id = item.Id }, new { @class = "compItem" }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id , courseid = Model.Id}, new { onclick = "return confirm('Are sure want to delete ?');" })           
                </td>
            </tr>
        }
    </table>
}
else
{
    <h3>This course hasn't Topics yet</h3>
}

@if (!User.IsInRole("listener"))
{
    @Html.ActionLink("To Course Page", "Edit", "Course", new {id = Model.Id}, null)
}

<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">

        $(function() {
            $.ajaxSetup({ cache: false });
            $(".compItem").click(function(e) {

                e.preventDefault();
                $.get(this.href,
                    function(data) {
                        $('#dialogContent').html(data);
                        $('#modDialog').modal('show');
                    });
            });
        });

        $(function() {
            $('.picker').datetimepicker(
                {
                    format: "DD/MM/YYYY"
                }).on('dp.change',
                function(e) {
                    $(this).data('DateTimePicker').hide();
                });
        });
    </script>
}

CourseManSystem/CourseManSystem/Views/Topic/Update.cshtml
@model CourseManSystem.Models.TopicPlModel
@{
    ViewBag.Title = "Update topic";
    Layout = null;
}

<div class="modal-content">
    
    <div class="modal-header">
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
    </div>
    <div class="modal-body">
        @using (Html.BeginForm("Update","Topic",FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>TopicPlModel</h4>
                <hr/>
                @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
                    </div>
                </div>
                @if (User.IsInRole("admin"))
                {
                    <div class="form-group">
                        @Html.LabelFor(model => model.Day, htmlAttributes: new {@class = "control-label col-md-2"})
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Day, new {htmlAttributes = new {@class = "form-control picker" } })
                            @Html.ValidationMessageFor(model => model.Day, "", new {@class = "text-danger"})
                        </div>
                    </div>    
                }
                <div>
                    @Html.HiddenFor(model => model.CourseId)
                </div>
                <div>
                    @Html.HiddenFor(model => model.Id)
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default"/>
                    </div>
                </div>
            </div>
        }
    </div>
</div>